### ISSUE TITLE
添加聊天窗口并与后端集成

### ISSUE THREAD

**Issue by MrCoder** [ZenGPT/confluence-gpt#65]
这是一个NodeJs Express服务器。

路由规则：

https://github.com/ZenGPT/confluence-gpt/blob/main/routes/index.js

**Comment by whimet** [comment]
目前的简单版本已经工作：

![Image](https://github.com/ZenGPT/confluence-gpt/assets/44074/cdfff25e-d273-4ae0-a7f1-e25f80a4e6c6)
