### ISSUE TITLE
将服务迁移到IPv6

### ISSUE THREAD

**Issue by zacker330** [ZenGPT/confluence-gpt#66]
# GOALS
1. Save cost of building product 

# STEPS
1. Make a service list that will be migrated from IPv4 to IPv6
 
- [ ]  diagramly
- [ ] gpt-ace

3. Figure the methods out for the migration
5. Release a canary version of a small zenuml product
6. Migrate all products one by one

## METHOD
1. Nginx: [config Nginx instance to listen to IPv6 address](https://ipw.cn/doc/ipv6/server/nginx_ipv6.html)
2. DNS: add `AAAA` record

## Mac
If you cannot ssh to server through IPv6 in your Mac, you should have a try: 
1. https://remoooo.com/it/683.html
2. turn on ipv6 feature of your router in your home

**Comment by zacker330** [comment]
# Investigation of lightsail LB
## Cost
$18 / month

**Comment by whimet** [comment]
讨论之后决定目前不迁移到IPV6.

**Comment by zacker330** [comment]
> 讨论之后决定目前不迁移到IPV6.

diagramly和gptdock的域名已经迁移回IPv4
