### ISSUE TITLE
Macro Design

### ISSUE THREAD

**Issue by whimet** [ZenGPT/confluence-gpt#77]

**Comment by whimet** [comment]
当前的页面：

![Image](https://github.com/ZenGPT/confluence-gpt/assets/44074/26ed5e85-4665-4047-8985-0a68a526c2af)

**Comment by caju290989** [comment]
设计的链接⬇️

https://www.figma.com/file/ogTY44KEnU9wVzwezLR7g7/ZenUML-Design-library?type=design&node-id=2314%3A539&mode=design&t=llIuw1aqC3Kk8zvO-1

做了两个排版的设计⬇️


![Image](https://github.com/ZenGPT/confluence-gpt/assets/85163944/d8304de2-e74d-412b-a44a-f9d12d7489bc)
![Image](https://github.com/ZenGPT/confluence-gpt/assets/85163944/0fefd8dc-716c-4118-8cba-c2c1c241fa92)
![Image](https://github.com/ZenGPT/confluence-gpt/assets/85163944/f1c072cb-07ee-4bad-b4ef-c80c9efa044e)

**Comment by caju290989** [comment]
https://www.figma.com/file/ogTY44KEnU9wVzwezLR7g7/ZenUML-Design-library?type=design&node-id=2314%3A539&mode=design&t=llIuw1aqC3Kk8zvO-1

按照上一次的讨论更新了设计：

1. Macro上移除 "text to content" section，产品专注在"code / draw to diagram"；

2. "Close" 按钮根据Atlassian 的 design Dos & Don't 的建议，改成"Back to Confluence".

3. 主要交互区上，
     - 把default状态下文案的“ No content yet" 改成 “Create and generate editable diagrams by text or drop 
        in an image.” 告知用户产品的功能;
     - 决定用左右布局（左边code / 右边diagram；
     - 在diagram生成后的交互区上，增加文案鼓励用户保存后使用full editor去编辑，只展示一个"Add to 
        confluence"按钮。
     - 对话输入框，和输出区域宽度增大方便更多地展示完整的diagram sequence；
     - 输入框里的 发送指令 "Send"按钮 文案改成“ Generate Diagram";
     - 输入框提示词从“Write a job description for Senior Devops Engineer" 改成生成diagram的提示词去“教 
       育”鼓励用户：“ e.g. Create a chatbot architecture for a personal banking“ （prompt 内容可讨论）;

**Comment by caju290989** [comment]
![Image](https://github.com/ZenGPT/confluence-gpt/assets/85163944/85ba04de-d886-4e62-a23e-b49571d93da4)
![Image](https://github.com/ZenGPT/confluence-gpt/assets/85163944/2ab3be1d-5403-4b00-af43-ed2c59e44497)

**Comment by caju290989** [comment]
![Image](https://github.com/ZenGPT/confluence-gpt/assets/85163944/1acc258f-1600-497e-930b-a5d517dd9914)



![Image](https://github.com/ZenGPT/confluence-gpt/assets/85163944/3a90cdff-0682-462c-af99-ffdc3d1b9594)
![Image](https://github.com/ZenGPT/confluence-gpt/assets/85163944/4873c9dc-7566-4b65-9579-0d331cef777d)

**Comment by caju290989** [comment]
13 Mar更新：

https://www.figma.com/file/ogTY44KEnU9wVzwezLR7g7/ZenUML-Design-library?type=design&node-id=2314%3A539&mode=design&t=anNGyojiGhfetKus-1

按照meeting讨论的，把Macro界面调整成：
1. 左边是Diagram editor /右边是 text history （每个section title的名字周六讨论）
2. 右边的text history提供隐藏 / 展开的功能， 隐藏/展开的箭头 鼠标hover的时候有tooltip展示。


![Image](https://github.com/ZenGPT/confluence-gpt/assets/85163944/43ae4df7-492c-41a0-8f8a-6066861d42f8)
![Image](https://github.com/ZenGPT/confluence-gpt/assets/85163944/94971cf0-488c-4ecb-ae6a-a19ccfd72eff)
![Image](https://github.com/ZenGPT/confluence-gpt/assets/85163944/83bde290-bbc3-4536-ab4f-c8c52b70b97f)
![Image](https://github.com/ZenGPT/confluence-gpt/assets/85163944/9c3f67a8-0944-49c7-8e46-e9423d8900c2)
